title: Jarno Luukkonen @ jarnoluu
email: luukkonen.jarno@gmail.com
description: >-
  Programming. Sql. Linux. Design. Stuff.
baseurl: ""
url: "http://jarnoluu.com"
excerpt_separator: <!--more-->
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
menu:
  - title: Blog
    url: /
    icon: comment
  - title: Projects
    url: /projects/
    icon: wrench
  - title: Designs
    url: /designs/
    icon: pencil
date_format: "%-d %b, %Y"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
