title: jarnoluu
email: luukkonen.jarno@gmail.com
description: >-
  Programming. Sql. Linux. Design. Stuff.
baseurl: ""
url: ""
excerpt_separator: <!--more-->
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
menu:
  - title: Blog
    url: /
    icon: comment
  - title: Projects
    url: /projects.html
    icon: wrench
  - title: Designs
    url: /designs.html
    icon: pencil

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
